# Generated by Django 5.1.1 on 2024-10-29 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_tasks_category_tasks_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='progress_percentage',
            field=models.IntegerField(default=0),
        ),
    ]
